#!/usr/bin/env bash
# migrate-brain-dir.sh — one-shot migration for the v1.0.0-rc4 directory rename
#                       (thoughts/ → project-brain/).
#
# What this does (in order):
#   1. Verifies the target is an rc3-or-earlier brain (has a thoughts/ directory
#      with a CONVENTIONS.md inside it).
#   2. git-mv thoughts/ → project-brain/ (preserving history if the brain is a
#      git repo; plain mv otherwise).
#   3. sed-replace `thoughts/` → `project-brain/` inside markdown + yaml files
#      within the migrated brain. Paths elsewhere in the repo are the user's
#      responsibility.
#   4. sed-replace `~/.ai/projects.yaml` → `~/.config/project-brain/projects.yaml`
#      in any lingering references inside the brain.
#   5. Writes a minimal <brain>/config.yaml stub if one doesn't exist.
#   6. Appends recommended .gitignore lines for transcript.md + attachments/
#      at the repo root if a .gitignore exists.
#   7. Runs verify-tree to confirm the migrated brain validates clean.
#
# What this does NOT do:
#   - Move ~/.ai/projects.yaml → ~/.config/project-brain/projects.yaml. You do
#     that yourself (it's optional anyway in rc4 — see CONVENTIONS § 2).
#   - Commit the changes. Review the diff, then commit yourself.
#
# Usage:   ./scripts/migrate-brain-dir.sh [--project-root <path>]
#          Default --project-root is $PWD.
#
# Exit codes:
#   0  migration complete, brain validates
#   1  validator reported errors after migration (brain state preserved; review)
#   2  invocation error (missing arg, no thoughts/ dir, refused to clobber, etc.)

set -euo pipefail

PROJECT_ROOT="${PWD}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="$2"; shift 2 ;;
    --project-root=*)
      PROJECT_ROOT="${1#*=}"; shift ;;
    -h|--help)
      head -n 35 "$0"; exit 0 ;;
    *)
      echo "error: unknown arg: $1" >&2; exit 2 ;;
  esac
done

cd "$PROJECT_ROOT"

# ---- 1. sanity checks ------------------------------------------------------
if [[ ! -d "thoughts" ]]; then
  echo "error: no thoughts/ directory at $PROJECT_ROOT — nothing to migrate." >&2
  exit 2
fi
if [[ ! -f "thoughts/CONVENTIONS.md" ]]; then
  echo "error: thoughts/CONVENTIONS.md missing — refuse to migrate a non-brain dir." >&2
  exit 2
fi
if [[ -d "project-brain" ]]; then
  echo "error: project-brain/ already exists — migration refuses to clobber." >&2
  exit 2
fi

echo ":: rc3 → rc4 migration starting in $PROJECT_ROOT"

# ---- 2. directory rename ---------------------------------------------------
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo ":: renaming thoughts/ → project-brain/ (via git mv, history preserved)"
  git mv thoughts project-brain
else
  echo ":: renaming thoughts/ → project-brain/ (non-git)"
  mv thoughts project-brain
fi

# ---- 3 + 4. path-literal sweep --------------------------------------------
echo ":: rewriting path literals inside project-brain/"
if sed --version >/dev/null 2>&1; then
  SED_INPLACE=(sed -i)
else
  SED_INPLACE=(sed -i '')
fi

find project-brain -type f \( -name '*.md' -o -name '*.yaml' \) -print0 \
  | while IFS= read -r -d '' f; do
      "${SED_INPLACE[@]}" \
        -e 's|thoughts/|project-brain/|g' \
        -e 's|~/\.ai/projects\.yaml|~/.config/project-brain/projects.yaml|g' \
        "$f"
    done

# ---- 5. per-project config stub -------------------------------------------
if [[ ! -f "project-brain/config.yaml" ]]; then
  PRIMARY_ALIAS=""
  if ls project-brain/threads/*/thread.md >/dev/null 2>&1; then
    PRIMARY_ALIAS=$(
      grep -h '^primary_project:' project-brain/threads/*/thread.md 2>/dev/null \
        | head -1 | awk '{print $2}' | tr -d '"' || true
    )
  fi
  : "${PRIMARY_ALIAS:=$(basename "$PROJECT_ROOT" | tr '[:upper:] ' '[:lower:]-')}"
  cat > project-brain/config.yaml <<YAML
# project-brain rc4 config (generated by migrate-brain-dir.sh).
# Edit freely. This file is authoritative for this brain.
primary_project: ${PRIMARY_ALIAS}

# Cross-project aliases this brain references. Leave empty if none.
aliases: {}

# Operational knobs. Defaults shown.
verbosity: terse
transcript_logging: on
YAML
  echo ":: wrote stub project-brain/config.yaml (primary_project: ${PRIMARY_ALIAS})"
fi

# ---- 6. .gitignore touches -------------------------------------------------
if [[ -f ".gitignore" ]]; then
  if ! grep -q "project-brain/threads/\*/transcript.md" .gitignore; then
    cat >> .gitignore <<'GITIGNORE'

# project-brain rc4 defaults — transcripts + attachments
project-brain/threads/*/transcript.md
project-brain/threads/*/attachments/
project-brain/archive/*/transcript.md
project-brain/archive/*/attachments/
GITIGNORE
    echo ":: appended rc4 defaults to .gitignore"
  fi
fi

# ---- 7. post-migration validation ------------------------------------------
echo ":: running verify-tree on migrated brain"
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
if [[ -x "${SCRIPT_DIR}/verify-tree.py" ]]; then
  VERIFIER="${SCRIPT_DIR}/verify-tree.py"
elif command -v verify-tree >/dev/null 2>&1; then
  VERIFIER=$(command -v verify-tree)
else
  echo "warn: verify-tree not found on PATH; skipping post-migration validation." >&2
  echo "      Run it manually: python3 <pack>/scripts/verify-tree.py --brain ${PROJECT_ROOT}/project-brain"
  exit 0
fi

if python3 "${VERIFIER}" --brain "${PROJECT_ROOT}/project-brain" --format human; then
  echo ":: migration complete, brain validates clean."
  echo ":: review the diff, then commit:  git add -A && git commit -m 'migrate brain dir to rc4 layout'"
  exit 0
else
  echo "error: validator reported errors after migration; review and fix before committing." >&2
  exit 1
fi
